#!/bin/bash

# Функція для встановлення gitleaks
install_gitleaks() {
    # Визначення операційної системи
    OS=$(uname -s | tr '[:upper:]' '[:lower:]')

    # Визначення архітектури
    ARCH=$(uname -m)

    # Перевірка, чи вже встановлено gitleaks
    if ! command -v gitleaks &> /dev/null; then
        

    #  if [[ ! -f ./gitleaks ]]; then
        echo "Installing gitleaks..."
        # Завантажуємо останню версію gitleaks з GitHub
        # Отримуємо посилання для завантаження gitleaks
        download_link=$(curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep "${OS}_${ARCH}")

        # curl -s https://api.github.com/repos/gitleaks/gitleaks/releases/latest | grep browser_download_url | cut -d '"' -f 4 | grep "${OS}_${ARCH}" | wget -i - -O gitleaks.tag.gz -q

        # Розпаковуємо архів та переміщаємо gitleaks у відповідне місце
        # Розпакування архіву gitleaks

        # Перевіряємо, чи download_link містить значення
        if [[ ! -z "$download_link" ]]; then
            # Завантажуємо gitleaks
            wget "$download_link" -O gitleaks.tar.gz -q
            
            # Розпаковуємо архіву gitleaks
            if [[ "$download_link" == *".tar.gz" ]]; then
                tar -xf gitleaks.tar.gz gitleaks
            elif [[ "$download_link" == *".zip" ]]; then
                unzip gitleaks.tar.gz gitleaks
            fi

            # Видаляємо тимчасовий архів
            rm gitleaks.tar.gz
            
            # Зміщуємо gitleaks у відповідне місце
            # mv gitleaks /usr/local/bin/gitleaks

            # Надаємо права на виконання
            chmod +x gitleaks
            # chmod +x /usr/local/bin/gitleaks
        fi
    fi

}



# Перевірка, чи увімкнена перевірка gitleaks через git config
gitleaks_check_enabled=$(git config --get hooks.gitleaks.enable)

if [ "$gitleaks_check_enabled" != "true" ]; then
    echo "gitleaks check is disabled via git config. Skipping gitleaks check."
    exit 0
else 
    # Встановлення gitleaks
    install_gitleaks
fi

# Виконання gitleaks для перевірки наявності секретів
echo "Running gitleaks..."
gitleaks --path=. --verbose

# Якщо gitleaks знайшов секретні дані, відхиляємо коміт
if [ $? -ne 0 ]; then
    echo "Commit rejected: gitleaks found sensitive data."
    exit 1
fi

echo "No sensitive data found. Commit allowed."
exit 0
