variables:
  REPO: 'https://github.com/acvetochka/telbot'
  BRANCH: 'main'
  DOCKER_HOST: tcp://dockerhost:2375
  DOCKER_TLS_CERTDIR: ''
  DOCKER_DRIVER: overlay2
  REGISTRY: ghcr.io/acvetochka
  OS:
    value: 'linux'
    options:
      - 'linux'
      - 'apple'
      - 'windows'
    description: 'Pick OS'
  ARCH:
    value: 'amd64'
    options:
      - 'amd64'
      - 'arm64'
    description: 'Pick ARCH'

stages:
  - test
  - build
  - image

test:
  stage: test
  image: golang:latest
  script:
    - echo 'Testing started'
    - make test

build:
  stage: build
  before_script:
  - apt-get update -y
  - apt-get install -y make
  - apt-get install -y golang
  script:
    - echo 'Building binary for platform $OS on $ARCH started'
    - make OS=$OS ARCH=$ARCH

build_image:
  stage: image
  image: docker:24.0.6
  services:
    - name: docker:24.0.6-dind
      alias: dockerhost
      command: [ "--tls=false" ]
  before_script:
    - apk add --no-cache make
  script:
    - echo 'Building image for platform $OS on $ARCH started'
    - echo "$REGISTRY_PASS" | docker login -u $REGISTRY_USER --password-stdin $REGISTRY
    - make image OS=$OS ARCH=$ARCH
    - echo 'Pushing image for platform $OS on $ARCH started'
    - make OS=$OS ARCH=$ARCH image push
