# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "acvetochka/telbot"
  tag: "v1.0.1-f9b67ac"
  os: "linux"
  arch: "amd64"
secret:
  name: "telbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
