# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "acvetochka/telbot"
  tag: "v1.0.1-510d6d1"
  os: ""
  arch: ""
secret:
  name: "telbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
